from setuptools import find_namespace_packages, setup

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="log_db_parser",
    description="Driver to get values log messages from postgres SQL DB",
    use_scm_version={
        "write_to": "python/lsst/db/version.py",
        "write_to_template": scm_version_template,
    },
    setup_requires=["setuptools_scm"],
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    package_data={"": []},
    scripts=[],
    license="GPL",
    project_urls={
    },
)
